tweaks to LICENSE/README; test mostly work, but 4lzt has different grids in parallel vs serial

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,10 +24,10 @@ flibs_fftw="-lfftw"
 mpif90="mpif90"
 
 openmp='no'
-ompflag='-fopenmp -DOPENMP'
+ompflag=""
 fftw_flags=""
-mkl="yes"
-useopenblas="yes"
+mkl=""
+useopenblas="no"
 
 lapack="skip"
 blas="skip"
@@ -44,7 +44,7 @@ for var in "$@"; do
         --conda)
             conda="yes";;
         --openmp)
-            fftw_flags="--enable-openmp"
+            ompflag='-fopenmp -DOPENMP';
             openmp="yes";;
         --no-netcdf)
             bintraj="";;
@@ -63,16 +63,13 @@ for var in "$@"; do
             ompflag="-qopenmp -DOPENMP";;
         --no-rism)
             rism="";;
-        --no-mkl)
-            mkl="no";;
         --mpi)
-            fftw_flags="--enable-mpi=yes"
+            mpi="yes"
+            fftw_flags="--enable-mpi=yes $fftw_flags"
             mpiflag="-DMPI"
             flibs_fftw="-lfftw3_mpi -lfftw3 -lmpi"
             fc="$mpif90"
-            sfx=".MPI"
-            mkl="no"
-            /bin/rm -f src/fftw3_config.log;;
+            sfx=".MPI";;
         *)
             echo "Option $var not recognized"
             exit 1
@@ -86,7 +83,6 @@ if [ "$requested_help" = "yes" ] ; then
 	printf " --intel        use Intel compilers; default is gnu\n"
 	printf " --mpi          prepare for mpi build (must come after --intel)\n"
 	printf " --openmp       prepare for OMP build\n"
-	printf " --no-mkl       disable MKL, even for intel compilers\n"
     exit 0
 fi
 
@@ -97,9 +93,6 @@ msanderhome=`pwd`
 #------------------------------------------------------------------------------
 if [ ! -d bin ]; then
     mkdir bin
-fi
-if [ ! -d include ]; then
-    mkdir include
 fi
 if [ ! -d lib ]; then
     mkdir lib
@@ -160,6 +153,7 @@ if [ -z "$mklroot" -o "$mkl" == "no" ] ; then
    if [ ! -z "$GOTO" -a "$useopenblas" == "yes" ]; then
 
       echo "using OpenBLAS libraries in $GOTO"
+      useopenblas="yes"
       flibs_la="$GOTO -lpthread"
 
    else
@@ -176,48 +170,23 @@ if [ -z "$mklroot" -o "$mkl" == "no" ] ; then
       flibs_fftw="-lfftw3_omp $flibs_fftw"
    fi
 
-    if [ ! -s "lib/libfftw3.a" ]; then
-       printf "\nConfiguring fftw-3.3 (may be time-consuming)..."
-       enable_sse="--enable-sse=no --enable-sse2=no --enable-avx=no"
-       enable_sse="--enable-sse2=yes"
-       cd src/fftw-3.3 && \
-           ./configure --disable-doc --prefix=$msanderhome \
-           --libdir=$msanderhome/lib $fftw_flags \
-           --enable-static --enable-sse2=yes MPICC="$mpicc" \
-           CC="$cc" CFLAGS="-O2"  F77="$fc" FFLAGS="-O2" \
-           FLIBS="$flibs_arch"  > fftw3_config.log 2>&1
-         ncerror=$?
-       if [ $ncerror -gt 0 ]; then
-           echo "Error: FFTW configure returned $ncerror"
-           exit 1
-       else
-           echo "OK"
-       fi
-
-       # Build FFTW3
-       printf "Compiling the FFTW3 interface (may be time-consuming)..."
-       make install > fftw3.compile.log 2>&1
-       if [ $? -ne 0 ]; then
-         printf "\nError: FFTW3 compile failed.\n"
-         exit 1
-       else
-         printf "OK\n"
-      fi
-      cd ../..
-   else
-      echo "Using fftw-3.3 already built"
-   fi
-
 else
 
-  echo "Using MKL for BLAS/LAPACK/FFTW in $mklroot"
-  inc="-I$mklroot/include -I$mklroot/include/fftw"
-  lapack=skip
-  blas=skip
-  flibs_fftw=""
+  if [ "$mpi" == "yes" ]; then
+     echo "Using MKL for BLAS/LAPACK in $mklroot"
+     inc="-I$mklroot/include -I$msanderhome/include"
+     lapack=skip
+     blas=skip
+  else
+     echo "Using MKL for BLAS/LAPACK/FFTW in $mklroot"
+     inc="-I$mklroot/include -I$mklroot/include/fftw"
+     lapack=skip
+     blas=skip
+     flibs_fftw=""
+  fi
 
   # Determine how we are linking MKL
-  link_type='mkl'
+  link_type='line'    # always use this for now
   if  [ "$compiler" = 'gnu' ] ; then
     link_type='line'
   fi
@@ -299,8 +268,44 @@ else
   fi
 fi
 
-if [ "$openmp" = "no" ]; then
-   ompflag=""
+#--------------------------------------------------------------------------
+#  Configure and build FFTW3:
+#--------------------------------------------------------------------------
+if [ "$mpi" == "yes" -o -z "$mklroot" -o "$mkl" == "no" ]; then
+
+    if [ ! -s "lib/libfftw3.a" ] || \
+       [ "$mpi" == "yes" -a ! -s "lib/libfftw3_mpi.a" ] || \
+       [ "$openmp" == "yes" -a ! -s "lib/libfftw3_omp.a" ]; then
+       printf "\nConfiguring fftw-3.3 (may be time-consuming)..."
+       enable_sse="--enable-sse=no --enable-sse2=no --enable-avx=no"
+       enable_sse="--enable-sse2=yes"
+       cd src/fftw-3.3 && \
+           ./configure --disable-doc --prefix=$msanderhome \
+           --libdir=$msanderhome/lib --enable-openmp $fftw_flags \
+           --enable-static --enable-sse2=yes MPICC="$mpicc" \
+           CC="$cc" CFLAGS="-O2"  F77="$fc" FFLAGS="-O2" \
+           FLIBS="$flibs_arch"  > fftw3_config.log 2>&1
+         ncerror=$?
+       if [ $ncerror -gt 0 ]; then
+           echo "Error: FFTW configure returned $ncerror"
+           exit 1
+       else
+           echo "OK"
+       fi
+
+       # Build FFTW3
+       printf "Compiling the FFTW3 interface (may be time-consuming)..."
+       make install > fftw3.compile.log 2>&1
+       if [ $? -ne 0 ]; then
+         printf "\nError: FFTW3 compile failed.\n"
+         exit 1
+       else
+         printf "OK\n"
+      fi
+      cd ../..
+   else
+      echo "Using fftw-3.3 already built"
+   fi
 fi
 
 #--------------------------------------------------------------------------
@@ -378,7 +383,7 @@ COPTFLAGS=-O3 -mtune=native
 
 FC=$fc
 FFLAGS=$bintraj $inc $ompflag $mpiflag
-FLIBSF= $rism -lsqm -larpack -lsys $flibs_la $ompflag $flibs_fftw
+FLIBSF= $rism -lsqm -larpack -lsys $flibs_fftw $flibs_la $ompflag 
 FNOOPTFLAGS= -O0 -g
 FOPTFLAGS= -O3 -g -mtune=native
 
