tweak configure to allow arch to be specified

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,19 +5,19 @@ printf "configure script for msander\n\n"
 # Store the command
 command=`echo "$0 $*"`
 
-# set up defaults:
+#------------------------------------------------------------------------------
+#  Set up defaults:
+#------------------------------------------------------------------------------
 msanderhome=`pwd`
 verbose="@"
 enablempi=
 requested_help="no"
 clangf=""
 openblas="no"
-moft="moft"
 sfx=""
 gcc10f=""
 gcc10c=""
 longlines="-ffree-line-length-none"
-pythonv=`python --version 2>&1 | cut -c 8-10`
 debug="-DNDEBUG"
 fpic="-fPIC"
 
@@ -43,6 +43,11 @@ installtype="serial"
 
 cuda="no"
 cudaflags=''
+cudafflags=''
+cuda_arch=''
+cuda_arch_flags=''
+uspec_arch='false'
+cuda_prec='SPFP'
 
 lapack="skip"
 blas="skip"
@@ -55,12 +60,13 @@ netcdflibf=$netcdflibf_static
 #short_ene=short_ene_omp.o
 short_ene=short_ene.o   # short_ene_omp may slow things down or even crash
 
-#  process command-line flags:
-for var in "$@"; do
-    case "$var" in
+#------------------------------------------------------------------------------
+#  Process command-line flags:
+#------------------------------------------------------------------------------
+
+while [ $# -gt 0 ]; do
+    case "$1" in
         -h|-H|--h|--he|--hel|--help|-help)
-            requested_help="yes";;
-        -fullhelp|--full|--fullhelp|--full-h|--full-he|--full-hel|--full-help)
             requested_help="yes";;
         --verbose)
             verbose="";;
@@ -70,16 +76,13 @@ for var in "$@"; do
             ompflag='-fopenmp -DOPENMP';
             flibs_fftw="-lfftw3_omp $flibs_fftw"
             openmp="yes";;
-        --cuda-single)
+        --cuda)
             cuda="yes"
             installtype="cuda"
-            fpic=""
-            cudaflags="-DCUDA -DCUDA_PRECISION=Single";;
-        --cuda-double)
-            cuda="yes"
-            installtype="cuda"
-            fpic=""
-            cudaflags="-DCUDA -DCUDA_PRECISION=Double";;
+            cudafflags="-DCUDA"
+            fpic="";;
+        --prec)          shift; cuda_prec="$1";;
+        --arch)          shift; cuda_arch="$cuda_arch $1"; uspec_arch='true';;
         --gcc10)
             gcc10f="-Wno-argument-mismatch -fallow-argument-mismatch -fno-inline-arg-packing"
             gcc10c="-fcommon";;
@@ -118,6 +121,7 @@ for var in "$@"; do
             echo "Option $var not recognized"
             exit 1
     esac
+    shift
 done
 
 if [ "$requested_help" = "yes" ] ; then
@@ -127,10 +131,9 @@ if [ "$requested_help" = "yes" ] ; then
     printf "\n"
 	printf " --mpi          prepare for mpi build\n"
 	printf " --openmp       prepare for OMP build\n"
-	printf " --cuda-single  prepare for cuda-single precision build\n"
-	printf " --cuda-double  prepare for cuda-double precision build\n"
-    printf "                N.B.: nvcc must be compatible with gcc/icc:\n"
-    printf "                https://docs.nvidia.com/cuda/cuda-installation-guide-linux\n"
+	printf " --cuda         prepare for cuda build\n"
+    printf " --prec         [SPFP|DPFP], cuda precision, default is SPFP\n"
+    printf " --arch          <kepler|maxwell|pascal|volta|turing|ampere> #default is all\n"
     printf "\n"
 	printf " --mkl          use MKL routines from \$MKLROOT environment variable\n"
 	printf " --openblas     use BLAS routines from \$GOTO environment variable\n"
@@ -138,8 +141,6 @@ if [ "$requested_help" = "yes" ] ; then
 	printf " --static       use static linking (experiental)\n"
     printf " --full         install everything with a serial install\n"
     printf "\n"
-    printf "Notes: For GNU compilers, use versions 6 or greater\n"
-    printf "       Test suite requires a C-shell (csh/tcsh)\n"
     exit 0
 fi
 
@@ -492,6 +493,133 @@ if [ "$flibs_fftw" != "" ]; then
    fi
 fi
 
+#---------------------------------------------------------------------!
+# Check for CUDA tool kit and compiler                                !
+#---------------------------------------------------------------------!
+
+# this function sets the user defined cuda architecture flags, if specified
+set_uspec_arch(){
+  for carch in $cuda_arch; do
+    case "$carch" in
+      kepler)
+        echo "Configuring for SM3.0"
+        cuda_arch_flags="$cuda_arch_flags $sm30flags"
+        cuda_dc_flags='-Xptxas --disable-optimizer-constants';;
+      maxwell)
+        echo "Configuring for SM5.0"
+        cuda_arch_flags="$cuda_arch_flags $sm50flags"
+        cuda_dc_flags='-Xptxas --disable-optimizer-constants';;
+      pascal)
+        echo "Configuring for SM6.0"
+        cuda_arch_flags="$cuda_arch_flags $sm60flags"
+        cuda_dc_flags='-Xptxas --disable-optimizer-constants';;
+      volta)
+        echo "Configuring for SM7.0"
+        cuda_arch_flags="$cuda_arch_flags $sm70flags"
+        if [ `echo "$cudaversion < 10.0 "| bc` -gt 0 ]; then
+          cuda_dc_flags='-Xptxas --disable-optimizer-constants'
+        fi
+        ;;
+      turing)
+        echo "Configuring for SM7.5"
+        cuda_arch_flags="$cuda_arch_flags $sm75flags";;
+      ampere)
+        echo "Configuring for SM8.0"
+        cuda_arch_flags="$cuda_arch_flags $sm80flags";;
+    esac
+  done
+}
+
+if [ "$cuda" = 'yes' ]; then
+  if [ -z "$CUDA_HOME" ]; then
+    echo  "Error: CUDA_HOME environment variable is not set."
+    echo  "Please make sure CUDA toolkit is loaded."
+    exit 1
+  fi
+
+  if [ ! -x "$CUDA_HOME/bin/nvcc" ]; then
+    echo  "Error: nvcc compiler is not available in $CUDA_HOME/bin/"
+    exit 1
+  fi
+
+  if [ -z "$NVCC" ]; then nvcc="$CUDA_HOME/bin/nvcc"; else nvcc="$NVCC"; fi
+
+    #SM8.0 = A100
+    sm80flags='-gencode arch=compute_80,code=sm_80'
+    #SM7.5 = RTX20xx, Tesla T4, Quadro RTX, RTX Titan
+    sm75flags='-gencode arch=compute_75,code=sm_75'
+    #SM7.0 = V100, Titan V
+    sm70flags='-gencode arch=compute_70,code=sm_70'
+    #SM6.0 = GP100 / P100 = DGX-1
+    sm60flags='-gencode arch=compute_60,code=sm_60'
+    #SM5.0 = M40
+    sm50flags='-gencode arch=compute_50,code=sm_50'
+    #SM3.0 = K80, K40, K20
+    sm30flags='-gencode arch=compute_30,code=sm_30'
+
+    cudaversion=`$nvcc --version | awk '/release/{print substr($5,1,4)}'`
+
+    if [ "${cudaversion:0:2}" = "11" ]; then
+
+      echo "CUDA Version $cudaversion detected"
+
+      if [ "$uspec_arch" = 'true' ]; then
+        set_uspec_arch
+      else
+        echo "Configuring for SM5.0, SM6.0, SM7.0, SM7.5, SM8.0"
+        cuda_arch_flags="$sm50flags $sm60flags $sm70flags $sm75flags $sm80flags"
+        cuda_dc_flags='-Xptxas --disable-optimizer-constants'
+      fi
+
+    elif [ "${cudaversion:0:2}" = "10" ]; then
+      echo "CUDA Version $cudaversion detected"
+
+      if [ "$uspec_arch" = 'true' ]; then
+        set_uspec_arch
+      else
+        echo "Configuring for SM3.0, SM5.0, SM6.0, SM7.0 and SM7.5"
+        cuda_arch_flags="$sm30flags $sm50flags $sm60flags $sm70flags $sm75flags"
+        cuda_dc_flags='-Xptxas --disable-optimizer-constants'
+      fi
+
+    elif [ "${cudaversion:0:1}" = "9" ]; then
+      echo "CUDA Version $cudaversion detected"
+
+      if [ "$uspec_arch" = 'true' ]; then
+        set_uspec_arch
+      else
+        echo "Configuring for SM3.0, SM5.0, SM6.0 and SM7.0"
+        cuda_arch_flags="$sm30flags $sm50flags $sm60flags $sm70flags"
+        cuda_dc_flags='-Xptxas --disable-optimizer-constants'
+      fi
+
+    elif [ "${cudaversion:0:1}" = "8" ]; then
+      echo "CUDA Version $cudaversion detected"
+
+      if [ "$uspec_arch" = 'true' ]; then
+        set_uspec_arch
+      else
+        echo "Configuring for SM3.0, SM5.0, SM6.0"
+        cuda_arch_flags="$sm30flags $sm50flags $sm60flags"
+        cuda_dc_flags='-Xptxas --disable-optimizer-constants'
+      fi
+
+    else
+      echo  "Error: Unsupported CUDA version $cudaversion detected. "
+      echo  "       requires at least CUDA version 8.0 "
+      exit 1
+    fi
+
+    if [ "$cuda_prec" = 'SPFP' ]; then
+       prec_model=-DCUDA_PRECISION=Single
+       printf "Using SPFP precision model\n"
+    else
+       prec_model=-DCUDA_PRECISION=Double
+       printf "Using DPFP precision model\n"
+    fi
+
+fi
+
 #--------------------------------------------------------------------------
 #  create the config.h file:
 #--------------------------------------------------------------------------
@@ -564,7 +692,8 @@ VB=$verbose
 INSTALLTYPE=$installtype
 
 # CUDA:
-CUDAFLAGS=$cudaflags
+CUDAFLAGS=$prec_model $cuda_arch_flags $cuda_dc_flags
+CUDAFFLAGS=$cudafflags
 
 # PLUMED related variables:
 PLUMED_INCLUDE_FILE=
