update tests to indicate netcdf is available

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,14 +20,13 @@ mpicc="mpicc"
 fc="gfortran"
 flibs_arch="-lgfortran -w"
 flibs_la=""
-flibs_fftw="-lfftw"
+flibs_fftw="-lfftw3"
 mpif90="mpif90"
 
 openmp='no'
 ompflag=""
 fftw_flags=""
 mkl=""
-useopenblas="no"
 
 lapack="skip"
 blas="skip"
@@ -45,6 +44,7 @@ for var in "$@"; do
             conda="yes";;
         --openmp)
             ompflag='-fopenmp -DOPENMP';
+            flibs_fftw="-lfftw3_omp -lfftw3"
             openmp="yes";;
         --no-netcdf)
             bintraj="";;
@@ -59,7 +59,6 @@ for var in "$@"; do
             fc="ifort"
             mpif90="mpiifort"
             flibs_arch="-lifport -lifcore -lsvml"
-            useopenblas="no"
             ompflag="-qopenmp -DOPENMP";;
         --no-rism)
             rism="";;
@@ -141,7 +140,7 @@ fi
 #--------------------------------------------------------------------------
 
 # Determine MKL home directory
-  mklroot=''
+mklroot=''
 if [ ! -z "$MKLROOT" ] ; then
     mklroot=$MKLROOT
 elif [ ! -z "$MKL_HOME" ] ; then
@@ -150,10 +149,9 @@ fi
 
 if [ -z "$mklroot" -o "$mkl" == "no" ] ; then
 
-   if [ ! -z "$GOTO" -a "$useopenblas" == "yes" ]; then
+   if [ ! -z "$GOTO" ]; then
 
       echo "using OpenBLAS libraries in $GOTO"
-      useopenblas="yes"
       flibs_la="$GOTO -lpthread"
 
    else
@@ -166,9 +164,6 @@ if [ -z "$mklroot" -o "$mkl" == "no" ] ; then
    fi
 
    inc="-I$msanderhome/include"
-   if [ "$openmp" = "yes" ]; then
-      flibs_fftw="-lfftw3_omp $flibs_fftw"
-   fi
 
 else
 
@@ -269,6 +264,67 @@ else
 fi
 
 #--------------------------------------------------------------------------
+#  Configure and build netcdf:
+#--------------------------------------------------------------------------
+if [ "$bintraj" == "-DBINTRAJ" ] && \
+   [ ! -s "lib/libnetcdf.a" ]; then
+   cd src/netcdf-c-4.7.2
+   printf "Configuring the NetCDF C interface...\n"
+   make clean > /dev/null 2>&1
+   ./configure CC="$cc" CFLAGS="" LDFLAGS="" \
+      --prefix=$msanderhome --disable-netcdf-4 --disable-dap \
+      --disable-shared --disable-doxygen > ../netcdf_c.config.log 2>&1
+   ncerror=$?
+   if [ $ncerror -gt 0 ]; then
+       echo "Error: NetCDF configure failed!  Check netcdf_c.config.log"
+       exit 1
+   else
+       echo "OK"
+   fi
+   # The NetCDF C interface MUST be present prior to configuring the
+   # Fortran interface, so build it now.
+   printf "Compiling the NetCDF C interface...\n"
+   make install > ../netcdf_c.compile.log 2>&1
+   if [ $? -ne 0 ]; then
+       echo "Error: NetCDF compile failed!  Check netcdf_c.compile.log"
+       exit 1
+   else
+       echo "OK"
+   fi
+   # NetCDF Fortran configure/build
+   cd ../netcdf-fortran-4.5.2
+   # The NetCDF Fortran config script will need access to the C library.
+   export LD_LIBRARY_PATH="$msanderhome/lib:$LD_LIBRARY_PATH"
+   printf "Configuring the NetCDF Fortran interface...\n"
+   make clean > /dev/null 2>&1
+   ./configure  CC="$cc" CFLAGS="" \
+                  LDFLAGS="-L$msanderhome/lib $ldflags" \
+                  CPPFLAGS="-I$msanderhome/include" \
+                  FC="$fc" FCFLAGS="" \
+                  F77="$fc" FFLAGS="" --disable-shared  --disable-doxygen \
+                  --prefix=$msanderhome >> ../netcdf_f.config.log 2>&1
+   ncerror=$?
+   if [ $ncerror -gt 0 ]; then
+       echo "Error: NetCDF configure failed!  Check netcdf_f.config.log"
+       exit 1
+   else
+       echo "OK"
+   fi
+   # Build the fortran interface
+   printf "Compiling the NetCDF Fortran interface...\n"
+   make install > ../netcdf_f.compile.log 2>&1
+   if [ $? -ne 0 ]; then
+     echo "Error: NetCDF Fortran compile failed!  Check netcdf_f.compile.log"
+     exit 1
+   else
+       echo "OK"
+   fi
+   cd ../..
+else
+   echo "Using the existing netcdf libraries"
+fi
+
+#--------------------------------------------------------------------------
 #  Configure and build FFTW3:
 #--------------------------------------------------------------------------
 if [ "$mpi" == "yes" -o -z "$mklroot" -o "$mkl" == "no" ]; then
@@ -276,7 +332,7 @@ if [ "$mpi" == "yes" -o -z "$mklroot" -o "$mkl" == "no" ]; then
     if [ ! -s "lib/libfftw3.a" ] || \
        [ "$mpi" == "yes" -a ! -s "lib/libfftw3_mpi.a" ] || \
        [ "$openmp" == "yes" -a ! -s "lib/libfftw3_omp.a" ]; then
-       printf "\nConfiguring fftw-3.3 (may be time-consuming)..."
+       printf "\nConfiguring fftw-3.3..."
        enable_sse="--enable-sse=no --enable-sse2=no --enable-avx=no"
        enable_sse="--enable-sse2=yes"
        cd src/fftw-3.3 && \
@@ -294,7 +350,7 @@ if [ "$mpi" == "yes" -o -z "$mklroot" -o "$mkl" == "no" ]; then
        fi
 
        # Build FFTW3
-       printf "Compiling the FFTW3 interface (may be time-consuming)..."
+       printf "Compiling the FFTW3 interface..."
        make install > fftw3.compile.log 2>&1
        if [ $? -ne 0 ]; then
          printf "\nError: FFTW3 compile failed.\n"
@@ -304,7 +360,7 @@ if [ "$mpi" == "yes" -o -z "$mklroot" -o "$mkl" == "no" ]; then
       fi
       cd ../..
    else
-      echo "Using fftw-3.3 already built"
+      echo "Using the existing fftw3  libraries"
    fi
 fi
 
@@ -347,7 +403,7 @@ LDFLAGS=$ldflags
 EOF
 
 if [ "$bintraj" == "-DBINTRAJ" ]; then
-   echo "Using netcdf from $NETCDF_HOME"
+NETCDF_HOME=$msanderhome
 cat <<EOF >> src/config.h
 NETCDF=$NETCDF_HOME/include/netcdf.mod
 NETCDFLIB=$NETCDF_HOME/lib/libnetcdf.a
