variety of updates, keep 4amber files

diff --git a/src/xray/XrayPrep b/src/xray/XrayPrep
--- a/src/xray/XrayPrep
+++ b/src/xray/XrayPrep
@@ -30,24 +30,28 @@ clapp()
 EOF
 
 # next only needed for ions: how to automate?
-perl -pi -e 's/CL$/Cl-1/' ${id}_uc.pdb \
+perl -pi -e 's/CL$/Cl-1/;s/MG$/Mg+2/;' ${id}_uc.pdb \
      || { echo "  perl:  Program error"; exit 1; }
 
-/bin/rm -f ${id}_uc.parm7 foo.parm7
+/bin/rm -f ${id}_uc.parm7 foo1.parm7 foo.parm7
 
 phenix.python ./parmed -n <<EOF >> $id-prep.log \
      || { echo "  parmed:   Program error"; exit 1; }
 parm 4amber_$id.prmtop
-addPdb ${id}_uc.pdb elem
 lmod
 parmout foo.parm7
 go
 EOF
 
-$MSANDERHOME/bin/add_xray -i foo.parm7 -o ${id}_uc.parm7 >> $id-prep.log \
+$MSANDERHOME/bin/add_pdb -i foo.parm7 -p ${id}_uc.pdb -o foo1.parm7 >> $id-prep.log \
+     || { echo "  add_pdb: Program error"; exit 1; }
+
+$MSANDERHOME/bin/add_xray -i foo1.parm7 -o ${id}_uc.parm7 >> $id-prep.log \
      || { echo "  add_xray: Program error"; exit 1; }
 
 /bin/mv 4amber_$id.rst7 ${id}_uc.rst7
+
+exit
 
 #============================================================================
 echo "Making input mtz file"
@@ -69,16 +73,16 @@ echo "Expanding reflections to P1 symmetry"
 
 phenix.reflection_file_converter cdl_001.mtz --expand_to_p1 \
     --label="F-obs-filtered,SIGF-obs-filtered" --generate_r_free_flags  \
-    --r_free_flags_format=ccp4  --mtz=$id-P1.mtz >> $id-prep.log
+    --r_free_flags_format=ccp4  --mtz=tmp-P1.mtz >> $id-prep.log
 
 phenix.reflection_file_converter cdl_001.mtz \
     --label="F-obs-filtered,SIGF-obs-filtered" --generate_r_free_flags  \
-    --r_free_flags_format=ccp4  --mtz=$id.mtz >> $id-prep.log
+    --r_free_flags_format=ccp4  --mtz=tmp.mtz >> $id-prep.log
 
 #============================================================================
 echo "Making the P1-sf.dat file"
 #  convert to formatted file:
-phenix.mtz.dump -c -f s $id-P1.mtz  | tr ',' '\t' > $id-P1.fmtz \
+phenix.mtz.dump -c -f s tmp-P1.mtz  | tr ',' '\t' > $id-P1.fmtz \
      || { echo "  phenix.mtz.dump:  Program error"; exit 1; }
 
 #  make the -sf.dat file needed by xray3:
@@ -93,7 +97,7 @@ cat tmp.dat >> $id-P1-sf.dat
 #============================================================================
 echo "Making the non-P1-sf.dat file"
 #  convert to formatted file:
-phenix.mtz.dump -c -f s $id.mtz  | tr ',' '\t' > $id.fmtz \
+phenix.mtz.dump -c -f s tmp.mtz  | tr ',' '\t' > $id.fmtz \
      || { echo "  phenix.mtz.dump:  Program error"; exit 1; }
 
 #  make the -sf.dat file needed by xray3:
@@ -106,6 +110,26 @@ echo "$nrefl 0" > $id-sf.dat
 cat tmp.dat >> $id-sf.dat
 
 #============================================================================
+echo "Running zero-cycle phenix.refine on P1-expanded structure:"
+
+cad hklin1 tmp.mtz hklout $id.mtz <<EOF >> $id-prep.log
+LABIN E1=F-obs-filtered E2=SIGF-obs-filtered E3=R-free-flags
+LABOUT E1=FOBS E2=SIGFOBS E3=R-free-flags
+EOF
+
+cad hklin1 tmp-P1.mtz hklout $id-P1.mtz <<EOF >> $id-prep.log
+LABIN E1=F-obs-filtered E2=SIGF-obs-filtered E3=R-free-flags
+LABOUT E1=FOBS E2=SIGFOBS E3=R-free-flags
+EOF
+
+phenix.refine  \
+   ${id}_uc.pdb $id-P1.mtz $ciffiles \
+   refinement.main.number_of_macro_cycles=0 \
+   prefix=cdl serial=2 \
+   write_geo=False cdl=True --overwrite >> $id-prep.log \
+     || { echo "  phenix.refine:  Program error"; exit 1; }
+
+#============================================================================
 echo "Done. Created 6 files:"
 echo "   ${id}_uc.parm7        Use this as the Amber prmtop file"
 echo "   ${id}_uc.rst7         Starting coordinates in Amber restrt format"
@@ -116,5 +140,5 @@ echo "   ${id}-prep.log        Log file: examine this if problems arise"
 
 #============================================================================
 # clean up
-/bin/rm -f tmp.dat $id-sf.mtz cdl_data.mtz $id.fmtz $id-P1.fmtz parmed \
-     cdl_00* *.order 4phenix_$id.pdb 4amber_$id.prmtop foo*.parm7 build_uc
+/bin/rm -f tmp* $id-sf.mtz cdl_data.mtz $id.fmtz $id-P1.fmtz parmed \
+     cdl_00* foo*.parm7 build_uc
