make both P1 and non-P1 -sf.dat files; other tweaks

diff --git a/src/xray/XrayPrep b/src/xray/XrayPrep
--- a/src/xray/XrayPrep
+++ b/src/xray/XrayPrep
@@ -14,7 +14,17 @@ echo "Running phenix.AmberPrep"
 phenix.AmberPrep $id.pdb >> $id-prep.log \
      || { echo "  phenix.AmberPrep:  Program error"; exit 1; }
 
-# create an interactive parmed script (why?)
+#  Here we need to edit the 4phenix_xxxx.pdb file to undo any changes
+#     that were made to handle carbodyrates; just change residue and
+#     atom names: no changes in order are allowed.
+
+/bin/mv 4phenix_$id.pdb 4phenix_${id}.pdb~
+/bin/cp ../phenix_amber/4phenix_$id.pdb .
+
+#============================================================================
+echo "creating ${id}_uc.parm7"
+# create an interactive parmed script (when run from phenix.python, will
+#       have the correct PYTHONPATH)
 cat <<EOF > parmed
 import os
 import sys
@@ -26,7 +36,6 @@ EOF
 perl -pi -e 's/CL$/Cl-1/' ${id}_uc.pdb \
      || { echo "  perl:  Program error"; exit 1; }
 
-echo "creating ${id}_uc.parm7"
 /bin/rm -f ${id}_uc.parm7 foo.parm7
 
 phenix.python ./parmed -n <<EOF >> $id-prep.log \
@@ -38,7 +47,7 @@ parmout foo.parm7
 go
 EOF
 
-add_xray -i foo.parm7 -o ${id}_uc.parm7 >> $id-prep.log \
+$MSANDERHOME/bin/add_xray -i foo.parm7 -o ${id}_uc.parm7 >> $id-prep.log \
      || { echo "  add_xray: Program error"; exit 1; }
 
 /bin/mv 4amber_$id.rst7 ${id}_uc.rst7
@@ -65,10 +74,29 @@ phenix.reflection_file_converter cdl_001.mtz --expand_to_p1 \
     --label="F-obs-filtered,SIGF-obs-filtered" --generate_r_free_flags  \
     --r_free_flags_format=ccp4  --mtz=$id-P1.mtz >> $id-prep.log
 
+phenix.reflection_file_converter cdl_001.mtz \
+    --label="F-obs-filtered,SIGF-obs-filtered" --generate_r_free_flags  \
+    --r_free_flags_format=ccp4  --mtz=$id.mtz >> $id-prep.log
+
 #============================================================================
-echo "Making the sf.dat file"
+echo "Making the P1-sf.dat file"
 #  convert to formatted file:
-phenix.mtz.dump -c -f s $id-P1.mtz  | tr ',' '\t' > $id.fmtz \
+phenix.mtz.dump -c -f s $id-P1.mtz  | tr ',' '\t' > $id-P1.fmtz \
+     || { echo "  phenix.mtz.dump:  Program error"; exit 1; }
+
+#  make the -sf.dat file needed by xray3:
+awk '{printf("%d\t%d\t%d\t%s\t%s\t%d\n", \
+      $1,$2,$3,$4,$5, $6>1 ? 1 : $6)}'  $id-P1.fmtz | tail +2 > tmp.dat \
+     || { echo "  awk:  Program error"; exit 1; }
+
+nrefl=`wc -l tmp.dat | awk '{print $1}'`
+echo "$nrefl 0" > $id-P1-sf.dat
+cat tmp.dat >> $id-P1-sf.dat
+
+#============================================================================
+echo "Making the non-P1-sf.dat file"
+#  convert to formatted file:
+phenix.mtz.dump -c -f s $id.mtz  | tr ',' '\t' > $id.fmtz \
      || { echo "  phenix.mtz.dump:  Program error"; exit 1; }
 
 #  make the -sf.dat file needed by xray3:
@@ -81,14 +109,15 @@ echo "$nrefl 0" > $id-sf.dat
 cat tmp.dat >> $id-sf.dat
 
 #============================================================================
-echo "Done. Created 5 files:"
+echo "Done. Created 6 files:"
 echo "   ${id}_uc.parm7        Use this as the Amber prmtop file"
 echo "   ${id}_uc.rst7         Starting coordinates in Amber restrt format"
 echo "   ${id}_uc.pdb          Use as pdb_infile"
-echo "   ${id}-sf.dat          Use as reflections_infile"
+echo "   ${id}-P1-sf.dat       Use as reflections_infile"
+echo "   ${id}-sf.dat          Use as alternate reflections_infile"
 echo "   ${id}-prep.log        Log file: examine this if problems arise"
 
 #============================================================================
 # clean up
-/bin/rm -f tmp.dat $id-sf.mtz cdl_data.mtz $id.fmtz parmed \
+/bin/rm -f tmp.dat $id-sf.mtz cdl_data.mtz $id.fmtz $id-P1.fmtz parmed \
      cdl_00* *.order 4phenix_$id.pdb 4amber_$id.prmtop foo*.parm7 build_uc
